Attribute VB_Name = "±äÁ¿ÉùÃ÷"
Global n As String
Global w As String
Global ent As String
Global sx As String
Global sy As String
Global startX As String
Global startY As String
Global aero As String
Global rou As String
Global outrgn As Long
Global spl As String
Global splt As String
Global sfly As String
Global sfl As String
Global gif As Boolean
Global gif_form1 As Boolean
Global gif_frmabout As Boolean
Global gif_gap As Boolean
Global gif_quickest As Boolean
Global gif_settings As Boolean
Global gif_wordbox As Boolean
